version: '3.7'

services:
  database:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: ROOT-PASSWORD
      MYSQL_USER: USERNAME
      MYSQL_PASSWORD: PASSWORD
      MYSQL_DATABASE: DATABASE-NAME
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql 

volumes:
  mysql: